from: https://jalammar.github.io/visual-numpy/

In [9]:
import numpy as np

In [10]:
data = np.array([1,2,3])
print(data.max(),'\t',data.min())


3 	 1


Trying out different ways to intialise numpy arrays

In [11]:
print(np.ones(3))
print(np.zeros(3))
print(np.random.random(3))
print(np.random.randint(20)) # Range 0,20

[1. 1. 1.]
[0. 0. 0.]
[0.67927946 0.38416027 0.75897495]
18


Array Arithemtic

In [12]:
data = np.array([1,2])
ones = np.ones(2)

print(data + ones)
print(data - ones)
print(data*ones)
print(data/ones)
print(data*1.6)

[2. 3.]
[0. 1.]
[1. 2.]
[1. 2.]
[1.6 3.2]


Slicing

In [13]:
data = np.array([1,2,3]) # Back to the original definition of data

print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])

1
2
[1 2]
[2 3]


Aggregation

In [14]:
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.prod()) # product - multiplying all the elements together
print(np.prod([1,2,3,4,5]))
print(data.std())
var = (((data[0]-data.mean())**2)+((data[1]-data.mean())**2)+((data[2]-data.mean())**2))/data.size
print(var)
std = np.sqrt(var)
print(std)

3
1
6
2.0
6
120
0.816496580927726
0.6666666666666666
0.816496580927726


Matrices

In [15]:
print(np.array([[1,2],[3,4]]))
print(np.ones([3,2]))
print(np.zeros([3,2]))
print(np.random.randint(0,20,[3,2]))

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 1 19]
 [18 18]
 [18  0]]


Matrix Arithmetic

In [16]:
data = np.array([[1,2],[3,4]])
ones = np.ones([2,2])


print(data+ones,'\n')

data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.ones([1,2])

print(ones_row,'\n')

data+ones_row

[[2. 3.]
 [4. 5.]] 

[[1. 1.]] 



array([[2., 3.],
       [4., 5.],
       [6., 7.]])

Dot Product

In [17]:
powers_of_ten = np.array([[10**0,10**1],[10**2,10**3],[10**4,10**5]])
data = np.array([1,2,3])

data.dot(powers_of_ten)

array([ 30201, 302010])

Matrix Aggregation - Same as vectors

In [18]:
data = np.array([[1,2,],[3,4],[5,6]])
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [19]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


Transposing and Reshaping

In [20]:
print(data,'\n')
print(data.T,'\n')

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]] 



Reshaping

In [21]:
data = np.array([1,2,3,4,5,6])
print(data,'\n')
print(data.reshape(2,3),'\n')
print(data.reshape(3,2),'\n')

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 



Adding a third dimension

In [22]:
data = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(data,'\n')
print(np.ones((4,3,2)))
print(np.zeros((4,3,2)))
print(np.random.randint(0,100,(4,3,2)))


[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[61  9]
  [60 42]
  [95 49]]

 [[24 34]
  [52 17]
  [13 25]]

 [[ 6  0]
  [22 46]
  [93 19]]

 [[67 37]
  [96 20]
  [88 98]]]


Mean Square Error Implementation
    

error = (1/n)*np.sum(np.square(predictions-labels))